### ISSUE TITLE
Fix manifpy test dependency

### ISSUE THREAD

**Issue by Giulero** [ami-iit/liecasadi#1]
In order to check the correctness of the computations, I wrote some tests against Manif.

It seems `manifpy` cannot be installed via PyPI. However, they provide installation instruction in https://github.com/artivis/manif/blob/devel/docs/pages/python/Quick-start.md.

Although I can install the library using conda on my system, I'm not able to move the same logic in a [workflow](https://github.com/ami-iit/liecasadi/blob/main/.github/workflows/tests.yml).
`manifpy` seems to be installed but it is not found:
```
ModuleNotFoundError: No module named 'manifpy'
```
Am I doing something wrong?

@traversaro @GiulioRomualdi  do you have any suggestions?

**Comment by traversaro** [comment]
@Giulero the workflow link is not pointing to the intended location I guess.

**Comment by Giulero** [comment]
Ops! Wrong copy-paste 
Now should be ok!

**Comment by traversaro** [comment]
So, the situation is a bit confusing as you currently have installed three python interpreter:
* The one that is installed via apt in the system (1)
* The one installed via conda as a dependency of `manifpy` (2)
* The one that is installed via `actions/setup-python` (3)

So, first of all let's decide which Python we want to use. As we want to install `manifpy` via conda-forge, I guess we want to install the python installed via conda (otherwise we could be using two different incompatible versions), i.e. (2). As a general note, I do not think there are many reason to use the Python installed via `actions/setup-python` (i.e. 3).
If we want to use conda, let's try to remove the installation of an additional python via `actions/setup-python`, and let's try again. To make sure of which python are you using, you can run `which python`. 

Furthermore, notice that if you want to use conda, you should run all the following steps with `shell: bash -l {0}`, or set it as default shell, see https://github.com/conda-incubator/setup-miniconda#use-a-default-shell and https://github.com/conda-incubator/setup-miniconda#important.

**Comment by Giulero** [comment]
Thanks @traversaro! I had to add a [few more lines](https://github.com/ami-iit/liecasadi/blob/63e90ed6388fb6fd5054cf8a00a613e45caedf3f/.github/workflows/tests.yml#L19-L24) and now the action proceeds :) 

Closing!
